update script

diff --git a/charts/scroll-sdk/templates/wait-l1-and-get-batch-info.yaml b/charts/scroll-sdk/templates/wait-l1-and-get-batch-info.yaml
--- a/charts/scroll-sdk/templates/wait-l1-and-get-batch-info.yaml
+++ b/charts/scroll-sdk/templates/wait-l1-and-get-batch-info.yaml
@@ -28,6 +28,14 @@ data:
     source /root/.bashrc
     foundryup
 
+    echo "Checking if cast is available..."
+    if command -v cast &> /dev/null; then
+      echo "cast is available"
+    else
+      echo "cast is not available. Foundry installation might have failed."
+      exit 1
+    fi
+
     # Get last finalized batch
     export LAST_FINALIZED_BATCH=$(cast call "${L1_MAINNET_SCROLL_CHAIN_PROXY_ADDR}" "lastFinalizedBatchIndex()(uint256)" --rpc-url ${L1_RPC_ENDPOINT} | awk '{print $1}')
 
